#ifndef VERSION_H
#define VERSION_H

#ifndef VERSION_STR_POSTFIX
#define VERSION_STR_POSTFIX ""
#endif /* VERSION_STR_POSTFIX */


#define VERSION_STR "2.0-WCD-pccg-3fa5284041e6871b2bcd971e8fbf9fa83aee0c9e" VERSION_STR_POSTFIX
#endif /* VERSION_H */
